name: Pytest

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install coverage-badge
        pip install mock
        pip install -r requirements.txt
    - name: Analysing the code with pytest
      run: |
        pytest --version
        pytest --cov
    - name: Creating coverage folder
      run: |
        mkdir -p coverage
    - name: Coverage Bagdge
      uses: tj-actions/coverage-badge-py@v1.8
      with:
        output: coverage/coverage.svg
    - name: Publish coverage report to coverage-badge branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: coverage-badge
        folder: coverage
        ssh-key: ${{ secrets.DEPLOY_KEY }}
